spring.application.name=DesignPattern


server.port=9292
server.servlet.context-path=/design-pattern

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#debug=true
spring.security.user.name=Username
spring.security.user.password=Password

bnxt.swagger.base-url=http://localhost:9292/design-pattern
